// <auto-generated />
namespace PassionProject_chatMessenger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class message_dtn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message_dtn));
        
        string IMigrationMetadata.Id
        {
            get { return "202306091645468_message_dtn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
